
// SPDX-License-Identifier: UNLICENSED
// Contract for MyToken2 (ERC20), generated by TokenFlow translator.
pragma solidity ^0.8.0;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
// Added import for IERC20 (needed for transferFrom in the main contract)
import "@openzeppelin/contracts/token/ERC20/IERC20.sol";

contract MyToken2 is ERC20, Ownable {
    /**
     * @dev Sets the values for {name} and {symbol}.
     * The owner of this contract will be the main MyModel contract.
     */
    constructor(address initialOwner) ERC20("MyToken2", "T2") Ownable(initialOwner) {}

    /**
     * @dev Creates `amount` tokens and assigns them to `to`, only callable by the owner (MyModel).
     */
    function mint(address to, uint256 amount) public virtual onlyOwner {
        _mint(to, amount);
    }

    /**
     * @dev Destroys `amount` tokens from `account`, only callable by the owner (MyModel).
     */
    function burn(address account, uint256 amount) public virtual onlyOwner {
        _burn(account, amount);
    }
}
