
// SPDX-License-Identifier: UNLICENSED
// Contract for Coupon (ERC721), generated by TokenFlow translator.
pragma solidity ^0.8.0;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/Counters.sol";
// Added import for IERC721 (needed for transferFrom in the main contract)
import "@openzeppelin/contracts/token/ERC721/IERC721.sol";

contract Coupon is ERC721, Ownable {
    using Counters for Counters.Counter;
    Counters.Counter private _tokenIdCounter;

    /**
     * @dev Structure to hold the attributes defined in the TokenFlow model for each NFT.
     */
    struct Attributes {
        string name;
        uint256 price;
    }

    /**
     * @dev Mapping from token ID to its attributes.
     */
    mapping(uint256 => Attributes) public tokenAttributes;

    /**
     * @dev Sets the values for {name} and {symbol}.
     * The owner of this contract will be the main MyModel contract.
     */
    constructor(address initialOwner) ERC721("Coupon", "COUPON") Ownable(initialOwner) {}

    /**
     * @dev Creates a new NFT with `tokenId` and assigns it to `to`, only callable by the owner (MyModel).
     * Sets the attributes based on the provided parameters.
     * @return The ID of the newly minted token.
     */
    function mint(address to, string memory _name, uint256 _price) public virtual onlyOwner returns (uint256) {
        // Start token IDs from 1 for safety, as 0 can be ambiguous
        _tokenIdCounter.increment();
        uint256 tokenId = _tokenIdCounter.current();

        _mint(to, tokenId);

        tokenAttributes[tokenId] = Attributes(_name, _price);

        return tokenId;
    }

    /**
     * @dev Destroys the NFT with `tokenId`, only callable by the owner (MyModel).
     */
    function burn(uint256 tokenId) public virtual onlyOwner {
        _burn(tokenId);
        // Delete attributes to potentially save gas and clear state
        delete tokenAttributes[tokenId];
    }

    // --- START FIX: Add attribute getters ---

/** @dev Getter for the 'name' attribute of a token. */
function getAttribute_name(uint256 tokenId) public view returns (string memory) {
    return tokenAttributes[tokenId].name;
}


/** @dev Getter for the 'price' attribute of a token. */
function getAttribute_price(uint256 tokenId) public view returns (uint256) {
    return tokenAttributes[tokenId].price;
}

    // --- END FIX ---
}
